services:
  web:
    build:
      context: angular
      target: dev-envs
    ports:
      - 80:4200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./angular:/project
      - /project/node_modules
